### ISSUE TITLE
Support `nouse_stdio`

### ISSUE THREAD

**Issue by hirschenberger** [obmarg/erlang_port#1]
Would it be possoble to support the `nouse_stdio` flag. This means the filedescriptors 4 and 5 are opened and used for IO. I like to use this flag, because it does not disturb communication when some Port is logging to stdout.

I once tried it myself but didn't find a way to open a Reader/Writer on an arbitrary integer FD.

**Comment by obmarg** [comment]
Hi @hirschenberger - thanks for raising this issue.  Must say, I wasn't expecting anyone to come across this project within a day of me publishing it.  Happy you did though 👍

Anyway, `nouse_stdio` is definitely something I want to support, but I also had a bit of difficulty figuring out how to do it.  I've got it figured out now though, so I'll try and add support for that today.  Also got a few refactors of the API in mind, so might do those today as well...

**Comment by obmarg** [comment]
@hirschenberger I've written up a bit on the API refactors I'm thinking of in #2 - if you have a few minutes I'd love to hear any thoughts or feedback you might have.  I'm fairly new to Rust, so not really sure how best to design APIs yet...

**Comment by hirschenberger** [comment]
Just a quick response, why not try to mimic the [Elixir.Port](https://hexdocs.pm/elixir/Port.html) module. I think it's easy to use your code when people feel familiar with the API they use on the other side of the FFI.
